---
pkg-name:         mariadb
display-name:     "MariaDB"
preferred:        1
extra_provides:   mariadb_55
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "5.5.45"
url:              "http://www.mariab.org"
source:           "https://downloads.mariadb.org/f/mariadb-%{version}/source/mariadb-%{version}.tar.gz"
src-dir:          "mariadb-%{version}"
lib-version:      18
lib-name:         mysqlclient
description:      'MariaDB is a backward compatible, drop-in replacement branch of the MySQL

Database Server. It includes all major open source storage engines, including

the Maria storage engine.'
---
