---
pkg-name:         mariadb_101
display-name:     "MariaDB"
preferred:        0
build_extras:     1
extra_provides:   mariadb_101
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "10.1.5"
srv-version:      "5.6.24"
url:              "https://www.mariadb.org"
source:           "https://downloads.mariadb.org/f/mariadb-%{version}/source/mariadb-%{version}.tar.gz"
src-dir:          "mariadb-%{version}"
lib-version:      18
lib-name:         mariadb101client
description:      'MariaDB is a backward compatible, drop-in replacement branch of the MySQL

Database Server. It includes all major open source storage engines, including

the Maria storage engine.'
---
