---
pkg-name:         mariadb-galera
display-name:     "MariaDB Galera"
systemd:          1
preferred:        0
use_extra_provides: 0
extra_provides:   mysql-cluster
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "10.0.14"
srv-version:      "5.6.20"
url:              "https://www.mariadb.org"
source:           "https://downloads.mariadb.org/interstitial/mariadb-galera-%{version}/source/mariadb-galera-%{version}.tar.gz"
src-dir:          "mariadb-%{version}"
lib-version:      18
lib-name:         mariadbgaleraclient
description:      'MariaDB Galera is a backward compatible, drop-in replacement branch of the

MySQL Database Server. It includes all major open source storage engines,

including the Maria storage engine. Also supports clustering.'
---
