---
pkg-name:         mariadb_100
display-name:     "MariaDB"
use_cmake:        1
systemd:          1
preferred:        0
use_extra_provides: 0
extra_provides:   mariadb_100
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "10.0.11"
srv-version:      "5.6.17"
url:              "http://www.mariab.org"
source:           "mariadb-%{version}.tar.bz2"
src-dir:          "mariadb-%{version}"
lib-version:      18
lib-name:         mariadb100client
description:      'MariaDB is a backward compatible, drop-in replacement branch of the MySQL

Database Server. It includes all major open source storage engines, including

the Maria storage engine.'
---
