---
pkg-name:         mariadb
display-name:     "MariaDB"
prefered:         0
use_cmake:        0
cluster:          0
builtin_plugins:  partition,csv,heap,aria,pbxt,myisam,myisammrg,xtradb
pkg-version:      "5.2.10"
srv-version:      "5.1.60"
url:              "http://www.mariab.org"
source:           "mariadb-%{version}.tar.bz2"
src-dir:          "mariadb-%{version}"
lib-version:      16
lib-name:         mariadbclient
description:      'MariaDB is a backward compatible, drop-in replacement branch of the MySQL

Database Server. It includes all major open source storage engines, including

the Maria storage engine.'
---
